### ISSUE TITLE
ModuleNotFoundError: No module named 'pysptk'

### ISSUE THREAD

**Issue by yishaicohe** [kan-bayashi/PytorchWaveNetVocoder#21]
hey,
i'm trying to implement your project but get in to some problems while running the 'Build SD model' ./run.sh (and the same problem for 'Build SI-CLOSE model' and 'Build SI-OPEN model')
This is my log file message:

 feature_extract.py --waveforms data/tr_slt/wav.scp --wavdir wav/tr_slt --hdf5dir hdf5/tr_slt --fs 16000 --shiftms 5 --minf0 120 --maxf0 275 --mcep_dim 24 --mcep_alpha 0.410 --highpass_cutoff 70 --fftl 1024 --n_jobs 10 
 Started at 22 10:05:24 IST 2018

Traceback (most recent call last):
  File "../../../src/bin/feature_extract.py", line 22, in <module>
    from sprocket.speech.feature_extractor import FeatureExtractor
  File "/PytorchWaveNetVocoder/tools/venv/lib/python3.6/site-packages/sprocket_vc-0.18-py3.6.egg/sprocket/speech/__init__.py", line 1, in <module>
    from .feature_extractor import FeatureExtractor
  File "/PytorchWaveNetVocoder/tools/venv/lib/python3.6/site-packages/sprocket_vc-0.18-py3.6.egg/sprocket/speech/feature_extractor.py", line 3, in <module>
    import pysptk
ModuleNotFoundError: No module named 'pysptk'
 Accounting: time=1 threads=1
 Ended (code 1) at 22 10:05:25 IST 2018, elapsed time 1 seconds

Does somebody know how to solve this?

thanks in advance.

**Comment by kan-bayashi** [comment]
Could you check that pysptk is successfully installed in virtualenv?
If pysptk is not installed in virtualenv, please install it as follows:
```
source tools/venv/bin/activate
pip install pysptk
```
